### ISSUE TITLE
prime512 is not prime

### ISSUE THREAD

**Issue by skrafft** [nijynot/shamir#1]
Hi,

While checking your implementation for a project, i noticed that you used prime512 as a mersenne number. The problem is that 2^512-1 is not a mersenne number and it's not prime either be cause it's 13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 which can be divided by 5.

You might want to use 2^521 - 1 which is a prime mersenne number. I'll submit a pull request if I have time in the near future.

**Comment by nijynot** [comment]
Resolved by e356699.
